/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain.tables.daos;


import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ru.xpendence.jooqexample.domain.tables.Cities;
import ru.xpendence.jooqexample.domain.tables.records.CitiesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CitiesDao extends DAOImpl<CitiesRecord, ru.xpendence.jooqexample.domain.tables.pojos.Cities, Long> {

    /**
     * Create a new CitiesDao without any configuration
     */
    public CitiesDao() {
        super(Cities.CITIES, ru.xpendence.jooqexample.domain.tables.pojos.Cities.class);
    }

    /**
     * Create a new CitiesDao with an attached configuration
     */
    public CitiesDao(Configuration configuration) {
        super(Cities.CITIES, ru.xpendence.jooqexample.domain.tables.pojos.Cities.class, configuration);
    }

    @Override
    public Long getId(ru.xpendence.jooqexample.domain.tables.pojos.Cities object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ru.xpendence.jooqexample.domain.tables.pojos.Cities> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Cities.CITIES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ru.xpendence.jooqexample.domain.tables.pojos.Cities> fetchById(Long... values) {
        return fetch(Cities.CITIES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ru.xpendence.jooqexample.domain.tables.pojos.Cities fetchOneById(Long value) {
        return fetchOne(Cities.CITIES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ru.xpendence.jooqexample.domain.tables.pojos.Cities> fetchOptionalById(Long value) {
        return fetchOptional(Cities.CITIES.ID, value);
    }

    /**
     * Fetch records that have <code>country_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ru.xpendence.jooqexample.domain.tables.pojos.Cities> fetchRangeOfCountryId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Cities.CITIES.COUNTRY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>country_id IN (values)</code>
     */
    public List<ru.xpendence.jooqexample.domain.tables.pojos.Cities> fetchByCountryId(Long... values) {
        return fetch(Cities.CITIES.COUNTRY_ID, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ru.xpendence.jooqexample.domain.tables.pojos.Cities> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Cities.CITIES.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<ru.xpendence.jooqexample.domain.tables.pojos.Cities> fetchByName(String... values) {
        return fetch(Cities.CITIES.NAME, values);
    }
}
