/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain.tables.daos;


import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ru.xpendence.jooqexample.domain.tables.Countries;
import ru.xpendence.jooqexample.domain.tables.records.CountriesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CountriesDao extends DAOImpl<CountriesRecord, ru.xpendence.jooqexample.domain.tables.pojos.Countries, Long> {

    /**
     * Create a new CountriesDao without any configuration
     */
    public CountriesDao() {
        super(Countries.COUNTRIES, ru.xpendence.jooqexample.domain.tables.pojos.Countries.class);
    }

    /**
     * Create a new CountriesDao with an attached configuration
     */
    public CountriesDao(Configuration configuration) {
        super(Countries.COUNTRIES, ru.xpendence.jooqexample.domain.tables.pojos.Countries.class, configuration);
    }

    @Override
    public Long getId(ru.xpendence.jooqexample.domain.tables.pojos.Countries object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ru.xpendence.jooqexample.domain.tables.pojos.Countries> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Countries.COUNTRIES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ru.xpendence.jooqexample.domain.tables.pojos.Countries> fetchById(Long... values) {
        return fetch(Countries.COUNTRIES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ru.xpendence.jooqexample.domain.tables.pojos.Countries fetchOneById(Long value) {
        return fetchOne(Countries.COUNTRIES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ru.xpendence.jooqexample.domain.tables.pojos.Countries> fetchOptionalById(Long value) {
        return fetchOptional(Countries.COUNTRIES.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ru.xpendence.jooqexample.domain.tables.pojos.Countries> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Countries.COUNTRIES.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<ru.xpendence.jooqexample.domain.tables.pojos.Countries> fetchByName(String... values) {
        return fetch(Countries.COUNTRIES.NAME, values);
    }

    /**
     * Fetch records that have <code>government_form BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ru.xpendence.jooqexample.domain.tables.pojos.Countries> fetchRangeOfGovernmentForm(String lowerInclusive, String upperInclusive) {
        return fetchRange(Countries.COUNTRIES.GOVERNMENT_FORM, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>government_form IN (values)</code>
     */
    public List<ru.xpendence.jooqexample.domain.tables.pojos.Countries> fetchByGovernmentForm(String... values) {
        return fetch(Countries.COUNTRIES.GOVERNMENT_FORM, values);
    }

    /**
     * Fetch records that have <code>population BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ru.xpendence.jooqexample.domain.tables.pojos.Countries> fetchRangeOfPopulation(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Countries.COUNTRIES.POPULATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>population IN (values)</code>
     */
    public List<ru.xpendence.jooqexample.domain.tables.pojos.Countries> fetchByPopulation(Integer... values) {
        return fetch(Countries.COUNTRIES.POPULATION, values);
    }
}
