/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain.routines;


import java.time.OffsetDateTime;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import ru.xpendence.jooqexample.domain.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgStatStatementsInfo extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.pg_stat_statements_info.dealloc</code>.
     */
    public static final Parameter<Long> DEALLOC = Internal.createParameter("dealloc", SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>public.pg_stat_statements_info.stats_reset</code>.
     */
    public static final Parameter<OffsetDateTime> STATS_RESET = Internal.createParameter("stats_reset", SQLDataType.TIMESTAMPWITHTIMEZONE(6), false, false);

    /**
     * Create a new routine call instance
     */
    public PgStatStatementsInfo() {
        super("pg_stat_statements_info", Public.PUBLIC);

        addOutParameter(DEALLOC);
        addOutParameter(STATS_RESET);
    }

    /**
     * Get the <code>dealloc</code> parameter OUT value from the routine
     */
    public Long getDealloc() {
        return get(DEALLOC);
    }

    /**
     * Get the <code>stats_reset</code> parameter OUT value from the routine
     */
    public OffsetDateTime getStatsReset() {
        return get(STATS_RESET);
    }
}
