/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.xpendence.jooqexample.domain.tables.Cities;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CitiesRecord extends UpdatableRecordImpl<CitiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.cities.id</code>.
     */
    public CitiesRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.cities.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.cities.country_id</code>.
     */
    public CitiesRecord setCountryId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.cities.country_id</code>.
     */
    public Long getCountryId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.cities.name</code>.
     */
    public CitiesRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.cities.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CitiesRecord
     */
    public CitiesRecord() {
        super(Cities.CITIES);
    }

    /**
     * Create a detached, initialised CitiesRecord
     */
    public CitiesRecord(Long id, Long countryId, String name) {
        super(Cities.CITIES);

        setId(id);
        setCountryId(countryId);
        setName(name);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CitiesRecord
     */
    public CitiesRecord(ru.xpendence.jooqexample.domain.tables.pojos.Cities value) {
        super(Cities.CITIES);

        if (value != null) {
            setId(value.getId());
            setCountryId(value.getCountryId());
            setName(value.getName());
            resetChangedOnNotNull();
        }
    }
}
