/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.xpendence.jooqexample.domain.tables.Countries;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CountriesRecord extends UpdatableRecordImpl<CountriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.countries.id</code>.
     */
    public CountriesRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.countries.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.countries.name</code>.
     */
    public CountriesRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.countries.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.countries.government_form</code>.
     */
    public CountriesRecord setGovernmentForm(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.countries.government_form</code>.
     */
    public String getGovernmentForm() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.countries.population</code>.
     */
    public CountriesRecord setPopulation(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.countries.population</code>.
     */
    public Integer getPopulation() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CountriesRecord
     */
    public CountriesRecord() {
        super(Countries.COUNTRIES);
    }

    /**
     * Create a detached, initialised CountriesRecord
     */
    public CountriesRecord(Long id, String name, String governmentForm, Integer population) {
        super(Countries.COUNTRIES);

        setId(id);
        setName(name);
        setGovernmentForm(governmentForm);
        setPopulation(population);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CountriesRecord
     */
    public CountriesRecord(ru.xpendence.jooqexample.domain.tables.pojos.Countries value) {
        super(Countries.COUNTRIES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setGovernmentForm(value.getGovernmentForm());
            setPopulation(value.getPopulation());
            resetChangedOnNotNull();
        }
    }
}
