/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain.tables.records;


import java.time.OffsetDateTime;

import org.jooq.impl.TableRecordImpl;

import ru.xpendence.jooqexample.domain.tables.PgStatStatementsInfo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgStatStatementsInfoRecord extends TableRecordImpl<PgStatStatementsInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pg_stat_statements_info.dealloc</code>.
     */
    public PgStatStatementsInfoRecord setDealloc(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements_info.dealloc</code>.
     */
    public Long getDealloc() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.pg_stat_statements_info.stats_reset</code>.
     */
    public PgStatStatementsInfoRecord setStatsReset(OffsetDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements_info.stats_reset</code>.
     */
    public OffsetDateTime getStatsReset() {
        return (OffsetDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgStatStatementsInfoRecord
     */
    public PgStatStatementsInfoRecord() {
        super(PgStatStatementsInfo.PG_STAT_STATEMENTS_INFO);
    }

    /**
     * Create a detached, initialised PgStatStatementsInfoRecord
     */
    public PgStatStatementsInfoRecord(Long dealloc, OffsetDateTime statsReset) {
        super(PgStatStatementsInfo.PG_STAT_STATEMENTS_INFO);

        setDealloc(dealloc);
        setStatsReset(statsReset);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PgStatStatementsInfoRecord
     */
    public PgStatStatementsInfoRecord(ru.xpendence.jooqexample.domain.tables.pojos.PgStatStatementsInfo value) {
        super(PgStatStatementsInfo.PG_STAT_STATEMENTS_INFO);

        if (value != null) {
            setDealloc(value.getDealloc());
            setStatsReset(value.getStatsReset());
            resetChangedOnNotNull();
        }
    }
}
