/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain.tables.records;


import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;

import ru.xpendence.jooqexample.domain.tables.PgStatStatements;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgStatStatementsRecord extends TableRecordImpl<PgStatStatementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pg_stat_statements.userid</code>.
     */
    public PgStatStatementsRecord setUserid(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.userid</code>.
     */
    public Long getUserid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.pg_stat_statements.dbid</code>.
     */
    public PgStatStatementsRecord setDbid(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.dbid</code>.
     */
    public Long getDbid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.pg_stat_statements.toplevel</code>.
     */
    public PgStatStatementsRecord setToplevel(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.toplevel</code>.
     */
    public Boolean getToplevel() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.pg_stat_statements.queryid</code>.
     */
    public PgStatStatementsRecord setQueryid(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.queryid</code>.
     */
    public Long getQueryid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.pg_stat_statements.query</code>.
     */
    public PgStatStatementsRecord setQuery(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.query</code>.
     */
    public String getQuery() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.pg_stat_statements.plans</code>.
     */
    public PgStatStatementsRecord setPlans(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.plans</code>.
     */
    public Long getPlans() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.pg_stat_statements.total_plan_time</code>.
     */
    public PgStatStatementsRecord setTotalPlanTime(Double value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.total_plan_time</code>.
     */
    public Double getTotalPlanTime() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.pg_stat_statements.min_plan_time</code>.
     */
    public PgStatStatementsRecord setMinPlanTime(Double value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.min_plan_time</code>.
     */
    public Double getMinPlanTime() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>public.pg_stat_statements.max_plan_time</code>.
     */
    public PgStatStatementsRecord setMaxPlanTime(Double value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.max_plan_time</code>.
     */
    public Double getMaxPlanTime() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>public.pg_stat_statements.mean_plan_time</code>.
     */
    public PgStatStatementsRecord setMeanPlanTime(Double value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.mean_plan_time</code>.
     */
    public Double getMeanPlanTime() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.pg_stat_statements.stddev_plan_time</code>.
     */
    public PgStatStatementsRecord setStddevPlanTime(Double value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.stddev_plan_time</code>.
     */
    public Double getStddevPlanTime() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>public.pg_stat_statements.calls</code>.
     */
    public PgStatStatementsRecord setCalls(Long value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.calls</code>.
     */
    public Long getCalls() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.pg_stat_statements.total_exec_time</code>.
     */
    public PgStatStatementsRecord setTotalExecTime(Double value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.total_exec_time</code>.
     */
    public Double getTotalExecTime() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>public.pg_stat_statements.min_exec_time</code>.
     */
    public PgStatStatementsRecord setMinExecTime(Double value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.min_exec_time</code>.
     */
    public Double getMinExecTime() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>public.pg_stat_statements.max_exec_time</code>.
     */
    public PgStatStatementsRecord setMaxExecTime(Double value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.max_exec_time</code>.
     */
    public Double getMaxExecTime() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>public.pg_stat_statements.mean_exec_time</code>.
     */
    public PgStatStatementsRecord setMeanExecTime(Double value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.mean_exec_time</code>.
     */
    public Double getMeanExecTime() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>public.pg_stat_statements.stddev_exec_time</code>.
     */
    public PgStatStatementsRecord setStddevExecTime(Double value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.stddev_exec_time</code>.
     */
    public Double getStddevExecTime() {
        return (Double) get(16);
    }

    /**
     * Setter for <code>public.pg_stat_statements.rows</code>.
     */
    public PgStatStatementsRecord setRows(Long value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.rows</code>.
     */
    public Long getRows() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_hit</code>.
     */
    public PgStatStatementsRecord setSharedBlksHit(Long value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_hit</code>.
     */
    public Long getSharedBlksHit() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_read</code>.
     */
    public PgStatStatementsRecord setSharedBlksRead(Long value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_read</code>.
     */
    public Long getSharedBlksRead() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_dirtied</code>.
     */
    public PgStatStatementsRecord setSharedBlksDirtied(Long value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_dirtied</code>.
     */
    public Long getSharedBlksDirtied() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_written</code>.
     */
    public PgStatStatementsRecord setSharedBlksWritten(Long value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_written</code>.
     */
    public Long getSharedBlksWritten() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_hit</code>.
     */
    public PgStatStatementsRecord setLocalBlksHit(Long value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_hit</code>.
     */
    public Long getLocalBlksHit() {
        return (Long) get(22);
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_read</code>.
     */
    public PgStatStatementsRecord setLocalBlksRead(Long value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_read</code>.
     */
    public Long getLocalBlksRead() {
        return (Long) get(23);
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_dirtied</code>.
     */
    public PgStatStatementsRecord setLocalBlksDirtied(Long value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_dirtied</code>.
     */
    public Long getLocalBlksDirtied() {
        return (Long) get(24);
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_written</code>.
     */
    public PgStatStatementsRecord setLocalBlksWritten(Long value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_written</code>.
     */
    public Long getLocalBlksWritten() {
        return (Long) get(25);
    }

    /**
     * Setter for <code>public.pg_stat_statements.temp_blks_read</code>.
     */
    public PgStatStatementsRecord setTempBlksRead(Long value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.temp_blks_read</code>.
     */
    public Long getTempBlksRead() {
        return (Long) get(26);
    }

    /**
     * Setter for <code>public.pg_stat_statements.temp_blks_written</code>.
     */
    public PgStatStatementsRecord setTempBlksWritten(Long value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.temp_blks_written</code>.
     */
    public Long getTempBlksWritten() {
        return (Long) get(27);
    }

    /**
     * Setter for <code>public.pg_stat_statements.blk_read_time</code>.
     */
    public PgStatStatementsRecord setBlkReadTime(Double value) {
        set(28, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.blk_read_time</code>.
     */
    public Double getBlkReadTime() {
        return (Double) get(28);
    }

    /**
     * Setter for <code>public.pg_stat_statements.blk_write_time</code>.
     */
    public PgStatStatementsRecord setBlkWriteTime(Double value) {
        set(29, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.blk_write_time</code>.
     */
    public Double getBlkWriteTime() {
        return (Double) get(29);
    }

    /**
     * Setter for <code>public.pg_stat_statements.temp_blk_read_time</code>.
     */
    public PgStatStatementsRecord setTempBlkReadTime(Double value) {
        set(30, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.temp_blk_read_time</code>.
     */
    public Double getTempBlkReadTime() {
        return (Double) get(30);
    }

    /**
     * Setter for <code>public.pg_stat_statements.temp_blk_write_time</code>.
     */
    public PgStatStatementsRecord setTempBlkWriteTime(Double value) {
        set(31, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.temp_blk_write_time</code>.
     */
    public Double getTempBlkWriteTime() {
        return (Double) get(31);
    }

    /**
     * Setter for <code>public.pg_stat_statements.wal_records</code>.
     */
    public PgStatStatementsRecord setWalRecords(Long value) {
        set(32, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.wal_records</code>.
     */
    public Long getWalRecords() {
        return (Long) get(32);
    }

    /**
     * Setter for <code>public.pg_stat_statements.wal_fpi</code>.
     */
    public PgStatStatementsRecord setWalFpi(Long value) {
        set(33, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.wal_fpi</code>.
     */
    public Long getWalFpi() {
        return (Long) get(33);
    }

    /**
     * Setter for <code>public.pg_stat_statements.wal_bytes</code>.
     */
    public PgStatStatementsRecord setWalBytes(BigDecimal value) {
        set(34, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.wal_bytes</code>.
     */
    public BigDecimal getWalBytes() {
        return (BigDecimal) get(34);
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_functions</code>.
     */
    public PgStatStatementsRecord setJitFunctions(Long value) {
        set(35, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_functions</code>.
     */
    public Long getJitFunctions() {
        return (Long) get(35);
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_generation_time</code>.
     */
    public PgStatStatementsRecord setJitGenerationTime(Double value) {
        set(36, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_generation_time</code>.
     */
    public Double getJitGenerationTime() {
        return (Double) get(36);
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_inlining_count</code>.
     */
    public PgStatStatementsRecord setJitInliningCount(Long value) {
        set(37, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_inlining_count</code>.
     */
    public Long getJitInliningCount() {
        return (Long) get(37);
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_inlining_time</code>.
     */
    public PgStatStatementsRecord setJitInliningTime(Double value) {
        set(38, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_inlining_time</code>.
     */
    public Double getJitInliningTime() {
        return (Double) get(38);
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_optimization_count</code>.
     */
    public PgStatStatementsRecord setJitOptimizationCount(Long value) {
        set(39, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_optimization_count</code>.
     */
    public Long getJitOptimizationCount() {
        return (Long) get(39);
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_optimization_time</code>.
     */
    public PgStatStatementsRecord setJitOptimizationTime(Double value) {
        set(40, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_optimization_time</code>.
     */
    public Double getJitOptimizationTime() {
        return (Double) get(40);
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_emission_count</code>.
     */
    public PgStatStatementsRecord setJitEmissionCount(Long value) {
        set(41, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_emission_count</code>.
     */
    public Long getJitEmissionCount() {
        return (Long) get(41);
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_emission_time</code>.
     */
    public PgStatStatementsRecord setJitEmissionTime(Double value) {
        set(42, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_emission_time</code>.
     */
    public Double getJitEmissionTime() {
        return (Double) get(42);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgStatStatementsRecord
     */
    public PgStatStatementsRecord() {
        super(PgStatStatements.PG_STAT_STATEMENTS);
    }

    /**
     * Create a detached, initialised PgStatStatementsRecord
     */
    public PgStatStatementsRecord(Long userid, Long dbid, Boolean toplevel, Long queryid, String query, Long plans, Double totalPlanTime, Double minPlanTime, Double maxPlanTime, Double meanPlanTime, Double stddevPlanTime, Long calls, Double totalExecTime, Double minExecTime, Double maxExecTime, Double meanExecTime, Double stddevExecTime, Long rows, Long sharedBlksHit, Long sharedBlksRead, Long sharedBlksDirtied, Long sharedBlksWritten, Long localBlksHit, Long localBlksRead, Long localBlksDirtied, Long localBlksWritten, Long tempBlksRead, Long tempBlksWritten, Double blkReadTime, Double blkWriteTime, Double tempBlkReadTime, Double tempBlkWriteTime, Long walRecords, Long walFpi, BigDecimal walBytes, Long jitFunctions, Double jitGenerationTime, Long jitInliningCount, Double jitInliningTime, Long jitOptimizationCount, Double jitOptimizationTime, Long jitEmissionCount, Double jitEmissionTime) {
        super(PgStatStatements.PG_STAT_STATEMENTS);

        setUserid(userid);
        setDbid(dbid);
        setToplevel(toplevel);
        setQueryid(queryid);
        setQuery(query);
        setPlans(plans);
        setTotalPlanTime(totalPlanTime);
        setMinPlanTime(minPlanTime);
        setMaxPlanTime(maxPlanTime);
        setMeanPlanTime(meanPlanTime);
        setStddevPlanTime(stddevPlanTime);
        setCalls(calls);
        setTotalExecTime(totalExecTime);
        setMinExecTime(minExecTime);
        setMaxExecTime(maxExecTime);
        setMeanExecTime(meanExecTime);
        setStddevExecTime(stddevExecTime);
        setRows(rows);
        setSharedBlksHit(sharedBlksHit);
        setSharedBlksRead(sharedBlksRead);
        setSharedBlksDirtied(sharedBlksDirtied);
        setSharedBlksWritten(sharedBlksWritten);
        setLocalBlksHit(localBlksHit);
        setLocalBlksRead(localBlksRead);
        setLocalBlksDirtied(localBlksDirtied);
        setLocalBlksWritten(localBlksWritten);
        setTempBlksRead(tempBlksRead);
        setTempBlksWritten(tempBlksWritten);
        setBlkReadTime(blkReadTime);
        setBlkWriteTime(blkWriteTime);
        setTempBlkReadTime(tempBlkReadTime);
        setTempBlkWriteTime(tempBlkWriteTime);
        setWalRecords(walRecords);
        setWalFpi(walFpi);
        setWalBytes(walBytes);
        setJitFunctions(jitFunctions);
        setJitGenerationTime(jitGenerationTime);
        setJitInliningCount(jitInliningCount);
        setJitInliningTime(jitInliningTime);
        setJitOptimizationCount(jitOptimizationCount);
        setJitOptimizationTime(jitOptimizationTime);
        setJitEmissionCount(jitEmissionCount);
        setJitEmissionTime(jitEmissionTime);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PgStatStatementsRecord
     */
    public PgStatStatementsRecord(ru.xpendence.jooqexample.domain.tables.pojos.PgStatStatements value) {
        super(PgStatStatements.PG_STAT_STATEMENTS);

        if (value != null) {
            setUserid(value.getUserid());
            setDbid(value.getDbid());
            setToplevel(value.getToplevel());
            setQueryid(value.getQueryid());
            setQuery(value.getQuery());
            setPlans(value.getPlans());
            setTotalPlanTime(value.getTotalPlanTime());
            setMinPlanTime(value.getMinPlanTime());
            setMaxPlanTime(value.getMaxPlanTime());
            setMeanPlanTime(value.getMeanPlanTime());
            setStddevPlanTime(value.getStddevPlanTime());
            setCalls(value.getCalls());
            setTotalExecTime(value.getTotalExecTime());
            setMinExecTime(value.getMinExecTime());
            setMaxExecTime(value.getMaxExecTime());
            setMeanExecTime(value.getMeanExecTime());
            setStddevExecTime(value.getStddevExecTime());
            setRows(value.getRows());
            setSharedBlksHit(value.getSharedBlksHit());
            setSharedBlksRead(value.getSharedBlksRead());
            setSharedBlksDirtied(value.getSharedBlksDirtied());
            setSharedBlksWritten(value.getSharedBlksWritten());
            setLocalBlksHit(value.getLocalBlksHit());
            setLocalBlksRead(value.getLocalBlksRead());
            setLocalBlksDirtied(value.getLocalBlksDirtied());
            setLocalBlksWritten(value.getLocalBlksWritten());
            setTempBlksRead(value.getTempBlksRead());
            setTempBlksWritten(value.getTempBlksWritten());
            setBlkReadTime(value.getBlkReadTime());
            setBlkWriteTime(value.getBlkWriteTime());
            setTempBlkReadTime(value.getTempBlkReadTime());
            setTempBlkWriteTime(value.getTempBlkWriteTime());
            setWalRecords(value.getWalRecords());
            setWalFpi(value.getWalFpi());
            setWalBytes(value.getWalBytes());
            setJitFunctions(value.getJitFunctions());
            setJitGenerationTime(value.getJitGenerationTime());
            setJitInliningCount(value.getJitInliningCount());
            setJitInliningTime(value.getJitInliningTime());
            setJitOptimizationCount(value.getJitOptimizationCount());
            setJitOptimizationTime(value.getJitOptimizationTime());
            setJitEmissionCount(value.getJitEmissionCount());
            setJitEmissionTime(value.getJitEmissionTime());
            resetChangedOnNotNull();
        }
    }
}
