/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.xpendence.jooqexample.domain.tables.Cities;
import ru.xpendence.jooqexample.domain.tables.Countries;
import ru.xpendence.jooqexample.domain.tables.PgStatStatements;
import ru.xpendence.jooqexample.domain.tables.PgStatStatementsInfo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.cities</code>.
     */
    public final Cities CITIES = Cities.CITIES;

    /**
     * The table <code>public.countries</code>.
     */
    public final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>public.pg_stat_statements</code>.
     */
    public final PgStatStatements PG_STAT_STATEMENTS = PgStatStatements.PG_STAT_STATEMENTS;

    /**
     * The table <code>public.pg_stat_statements_info</code>.
     */
    public final PgStatStatementsInfo PG_STAT_STATEMENTS_INFO = PgStatStatementsInfo.PG_STAT_STATEMENTS_INFO;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Cities.CITIES,
            Countries.COUNTRIES,
            PgStatStatements.PG_STAT_STATEMENTS,
            PgStatStatementsInfo.PG_STAT_STATEMENTS_INFO
        );
    }
}
