/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain;


import org.jooq.Configuration;

import ru.xpendence.jooqexample.domain.routines.PgStatStatementsInfo;
import ru.xpendence.jooqexample.domain.routines.PgStatStatementsReset;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>public.pg_stat_statements_info</code>
     */
    public static PgStatStatementsInfo pgStatStatementsInfo(
          Configuration configuration
    ) {
        PgStatStatementsInfo p = new PgStatStatementsInfo();

        p.execute(configuration);
        return p;
    }

    /**
     * Call <code>public.pg_stat_statements_reset</code>
     */
    public static void pgStatStatementsReset(
          Configuration configuration
        , Long userid
        , Long dbid
        , Long queryid
    ) {
        PgStatStatementsReset p = new PgStatStatementsReset();
        p.setUserid(userid);
        p.setDbid(dbid);
        p.setQueryid(queryid);

        p.execute(configuration);
    }
}
