/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain;


import ru.xpendence.jooqexample.domain.tables.Cities;
import ru.xpendence.jooqexample.domain.tables.Countries;
import ru.xpendence.jooqexample.domain.tables.PgStatStatements;
import ru.xpendence.jooqexample.domain.tables.PgStatStatementsInfo;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.cities</code>.
     */
    public static final Cities CITIES = Cities.CITIES;

    /**
     * The table <code>public.countries</code>.
     */
    public static final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>public.pg_stat_statements</code>.
     */
    public static final PgStatStatements PG_STAT_STATEMENTS = PgStatStatements.PG_STAT_STATEMENTS;

    /**
     * The table <code>public.pg_stat_statements_info</code>.
     */
    public static final PgStatStatementsInfo PG_STAT_STATEMENTS_INFO = PgStatStatementsInfo.PG_STAT_STATEMENTS_INFO;
}
