/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Cities implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long countryId;
    private String name;

    public Cities() {}

    public Cities(Cities value) {
        this.id = value.id;
        this.countryId = value.countryId;
        this.name = value.name;
    }

    public Cities(
        Long id,
        Long countryId,
        String name
    ) {
        this.id = id;
        this.countryId = countryId;
        this.name = name;
    }

    /**
     * Getter for <code>public.cities.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.cities.id</code>.
     */
    public Cities setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.cities.country_id</code>.
     */
    public Long getCountryId() {
        return this.countryId;
    }

    /**
     * Setter for <code>public.cities.country_id</code>.
     */
    public Cities setCountryId(Long countryId) {
        this.countryId = countryId;
        return this;
    }

    /**
     * Getter for <code>public.cities.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.cities.name</code>.
     */
    public Cities setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Cities other = (Cities) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.countryId == null) {
            if (other.countryId != null)
                return false;
        }
        else if (!this.countryId.equals(other.countryId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.countryId == null) ? 0 : this.countryId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Cities (");

        sb.append(id);
        sb.append(", ").append(countryId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
