/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Countries implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private String governmentForm;
    private Integer population;

    public Countries() {}

    public Countries(Countries value) {
        this.id = value.id;
        this.name = value.name;
        this.governmentForm = value.governmentForm;
        this.population = value.population;
    }

    public Countries(
        Long id,
        String name,
        String governmentForm,
        Integer population
    ) {
        this.id = id;
        this.name = name;
        this.governmentForm = governmentForm;
        this.population = population;
    }

    /**
     * Getter for <code>public.countries.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.countries.id</code>.
     */
    public Countries setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.countries.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.countries.name</code>.
     */
    public Countries setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.countries.government_form</code>.
     */
    public String getGovernmentForm() {
        return this.governmentForm;
    }

    /**
     * Setter for <code>public.countries.government_form</code>.
     */
    public Countries setGovernmentForm(String governmentForm) {
        this.governmentForm = governmentForm;
        return this;
    }

    /**
     * Getter for <code>public.countries.population</code>.
     */
    public Integer getPopulation() {
        return this.population;
    }

    /**
     * Setter for <code>public.countries.population</code>.
     */
    public Countries setPopulation(Integer population) {
        this.population = population;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Countries other = (Countries) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.governmentForm == null) {
            if (other.governmentForm != null)
                return false;
        }
        else if (!this.governmentForm.equals(other.governmentForm))
            return false;
        if (this.population == null) {
            if (other.population != null)
                return false;
        }
        else if (!this.population.equals(other.population))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.governmentForm == null) ? 0 : this.governmentForm.hashCode());
        result = prime * result + ((this.population == null) ? 0 : this.population.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Countries (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(governmentForm);
        sb.append(", ").append(population);

        sb.append(")");
        return sb.toString();
    }
}
