/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgStatStatements implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long userid;
    private Long dbid;
    private Boolean toplevel;
    private Long queryid;
    private String query;
    private Long plans;
    private Double totalPlanTime;
    private Double minPlanTime;
    private Double maxPlanTime;
    private Double meanPlanTime;
    private Double stddevPlanTime;
    private Long calls;
    private Double totalExecTime;
    private Double minExecTime;
    private Double maxExecTime;
    private Double meanExecTime;
    private Double stddevExecTime;
    private Long rows;
    private Long sharedBlksHit;
    private Long sharedBlksRead;
    private Long sharedBlksDirtied;
    private Long sharedBlksWritten;
    private Long localBlksHit;
    private Long localBlksRead;
    private Long localBlksDirtied;
    private Long localBlksWritten;
    private Long tempBlksRead;
    private Long tempBlksWritten;
    private Double blkReadTime;
    private Double blkWriteTime;
    private Double tempBlkReadTime;
    private Double tempBlkWriteTime;
    private Long walRecords;
    private Long walFpi;
    private BigDecimal walBytes;
    private Long jitFunctions;
    private Double jitGenerationTime;
    private Long jitInliningCount;
    private Double jitInliningTime;
    private Long jitOptimizationCount;
    private Double jitOptimizationTime;
    private Long jitEmissionCount;
    private Double jitEmissionTime;

    public PgStatStatements() {}

    public PgStatStatements(PgStatStatements value) {
        this.userid = value.userid;
        this.dbid = value.dbid;
        this.toplevel = value.toplevel;
        this.queryid = value.queryid;
        this.query = value.query;
        this.plans = value.plans;
        this.totalPlanTime = value.totalPlanTime;
        this.minPlanTime = value.minPlanTime;
        this.maxPlanTime = value.maxPlanTime;
        this.meanPlanTime = value.meanPlanTime;
        this.stddevPlanTime = value.stddevPlanTime;
        this.calls = value.calls;
        this.totalExecTime = value.totalExecTime;
        this.minExecTime = value.minExecTime;
        this.maxExecTime = value.maxExecTime;
        this.meanExecTime = value.meanExecTime;
        this.stddevExecTime = value.stddevExecTime;
        this.rows = value.rows;
        this.sharedBlksHit = value.sharedBlksHit;
        this.sharedBlksRead = value.sharedBlksRead;
        this.sharedBlksDirtied = value.sharedBlksDirtied;
        this.sharedBlksWritten = value.sharedBlksWritten;
        this.localBlksHit = value.localBlksHit;
        this.localBlksRead = value.localBlksRead;
        this.localBlksDirtied = value.localBlksDirtied;
        this.localBlksWritten = value.localBlksWritten;
        this.tempBlksRead = value.tempBlksRead;
        this.tempBlksWritten = value.tempBlksWritten;
        this.blkReadTime = value.blkReadTime;
        this.blkWriteTime = value.blkWriteTime;
        this.tempBlkReadTime = value.tempBlkReadTime;
        this.tempBlkWriteTime = value.tempBlkWriteTime;
        this.walRecords = value.walRecords;
        this.walFpi = value.walFpi;
        this.walBytes = value.walBytes;
        this.jitFunctions = value.jitFunctions;
        this.jitGenerationTime = value.jitGenerationTime;
        this.jitInliningCount = value.jitInliningCount;
        this.jitInliningTime = value.jitInliningTime;
        this.jitOptimizationCount = value.jitOptimizationCount;
        this.jitOptimizationTime = value.jitOptimizationTime;
        this.jitEmissionCount = value.jitEmissionCount;
        this.jitEmissionTime = value.jitEmissionTime;
    }

    public PgStatStatements(
        Long userid,
        Long dbid,
        Boolean toplevel,
        Long queryid,
        String query,
        Long plans,
        Double totalPlanTime,
        Double minPlanTime,
        Double maxPlanTime,
        Double meanPlanTime,
        Double stddevPlanTime,
        Long calls,
        Double totalExecTime,
        Double minExecTime,
        Double maxExecTime,
        Double meanExecTime,
        Double stddevExecTime,
        Long rows,
        Long sharedBlksHit,
        Long sharedBlksRead,
        Long sharedBlksDirtied,
        Long sharedBlksWritten,
        Long localBlksHit,
        Long localBlksRead,
        Long localBlksDirtied,
        Long localBlksWritten,
        Long tempBlksRead,
        Long tempBlksWritten,
        Double blkReadTime,
        Double blkWriteTime,
        Double tempBlkReadTime,
        Double tempBlkWriteTime,
        Long walRecords,
        Long walFpi,
        BigDecimal walBytes,
        Long jitFunctions,
        Double jitGenerationTime,
        Long jitInliningCount,
        Double jitInliningTime,
        Long jitOptimizationCount,
        Double jitOptimizationTime,
        Long jitEmissionCount,
        Double jitEmissionTime
    ) {
        this.userid = userid;
        this.dbid = dbid;
        this.toplevel = toplevel;
        this.queryid = queryid;
        this.query = query;
        this.plans = plans;
        this.totalPlanTime = totalPlanTime;
        this.minPlanTime = minPlanTime;
        this.maxPlanTime = maxPlanTime;
        this.meanPlanTime = meanPlanTime;
        this.stddevPlanTime = stddevPlanTime;
        this.calls = calls;
        this.totalExecTime = totalExecTime;
        this.minExecTime = minExecTime;
        this.maxExecTime = maxExecTime;
        this.meanExecTime = meanExecTime;
        this.stddevExecTime = stddevExecTime;
        this.rows = rows;
        this.sharedBlksHit = sharedBlksHit;
        this.sharedBlksRead = sharedBlksRead;
        this.sharedBlksDirtied = sharedBlksDirtied;
        this.sharedBlksWritten = sharedBlksWritten;
        this.localBlksHit = localBlksHit;
        this.localBlksRead = localBlksRead;
        this.localBlksDirtied = localBlksDirtied;
        this.localBlksWritten = localBlksWritten;
        this.tempBlksRead = tempBlksRead;
        this.tempBlksWritten = tempBlksWritten;
        this.blkReadTime = blkReadTime;
        this.blkWriteTime = blkWriteTime;
        this.tempBlkReadTime = tempBlkReadTime;
        this.tempBlkWriteTime = tempBlkWriteTime;
        this.walRecords = walRecords;
        this.walFpi = walFpi;
        this.walBytes = walBytes;
        this.jitFunctions = jitFunctions;
        this.jitGenerationTime = jitGenerationTime;
        this.jitInliningCount = jitInliningCount;
        this.jitInliningTime = jitInliningTime;
        this.jitOptimizationCount = jitOptimizationCount;
        this.jitOptimizationTime = jitOptimizationTime;
        this.jitEmissionCount = jitEmissionCount;
        this.jitEmissionTime = jitEmissionTime;
    }

    /**
     * Getter for <code>public.pg_stat_statements.userid</code>.
     */
    public Long getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>public.pg_stat_statements.userid</code>.
     */
    public PgStatStatements setUserid(Long userid) {
        this.userid = userid;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.dbid</code>.
     */
    public Long getDbid() {
        return this.dbid;
    }

    /**
     * Setter for <code>public.pg_stat_statements.dbid</code>.
     */
    public PgStatStatements setDbid(Long dbid) {
        this.dbid = dbid;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.toplevel</code>.
     */
    public Boolean getToplevel() {
        return this.toplevel;
    }

    /**
     * Setter for <code>public.pg_stat_statements.toplevel</code>.
     */
    public PgStatStatements setToplevel(Boolean toplevel) {
        this.toplevel = toplevel;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.queryid</code>.
     */
    public Long getQueryid() {
        return this.queryid;
    }

    /**
     * Setter for <code>public.pg_stat_statements.queryid</code>.
     */
    public PgStatStatements setQueryid(Long queryid) {
        this.queryid = queryid;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.query</code>.
     */
    public String getQuery() {
        return this.query;
    }

    /**
     * Setter for <code>public.pg_stat_statements.query</code>.
     */
    public PgStatStatements setQuery(String query) {
        this.query = query;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.plans</code>.
     */
    public Long getPlans() {
        return this.plans;
    }

    /**
     * Setter for <code>public.pg_stat_statements.plans</code>.
     */
    public PgStatStatements setPlans(Long plans) {
        this.plans = plans;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.total_plan_time</code>.
     */
    public Double getTotalPlanTime() {
        return this.totalPlanTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.total_plan_time</code>.
     */
    public PgStatStatements setTotalPlanTime(Double totalPlanTime) {
        this.totalPlanTime = totalPlanTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.min_plan_time</code>.
     */
    public Double getMinPlanTime() {
        return this.minPlanTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.min_plan_time</code>.
     */
    public PgStatStatements setMinPlanTime(Double minPlanTime) {
        this.minPlanTime = minPlanTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.max_plan_time</code>.
     */
    public Double getMaxPlanTime() {
        return this.maxPlanTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.max_plan_time</code>.
     */
    public PgStatStatements setMaxPlanTime(Double maxPlanTime) {
        this.maxPlanTime = maxPlanTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.mean_plan_time</code>.
     */
    public Double getMeanPlanTime() {
        return this.meanPlanTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.mean_plan_time</code>.
     */
    public PgStatStatements setMeanPlanTime(Double meanPlanTime) {
        this.meanPlanTime = meanPlanTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.stddev_plan_time</code>.
     */
    public Double getStddevPlanTime() {
        return this.stddevPlanTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.stddev_plan_time</code>.
     */
    public PgStatStatements setStddevPlanTime(Double stddevPlanTime) {
        this.stddevPlanTime = stddevPlanTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.calls</code>.
     */
    public Long getCalls() {
        return this.calls;
    }

    /**
     * Setter for <code>public.pg_stat_statements.calls</code>.
     */
    public PgStatStatements setCalls(Long calls) {
        this.calls = calls;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.total_exec_time</code>.
     */
    public Double getTotalExecTime() {
        return this.totalExecTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.total_exec_time</code>.
     */
    public PgStatStatements setTotalExecTime(Double totalExecTime) {
        this.totalExecTime = totalExecTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.min_exec_time</code>.
     */
    public Double getMinExecTime() {
        return this.minExecTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.min_exec_time</code>.
     */
    public PgStatStatements setMinExecTime(Double minExecTime) {
        this.minExecTime = minExecTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.max_exec_time</code>.
     */
    public Double getMaxExecTime() {
        return this.maxExecTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.max_exec_time</code>.
     */
    public PgStatStatements setMaxExecTime(Double maxExecTime) {
        this.maxExecTime = maxExecTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.mean_exec_time</code>.
     */
    public Double getMeanExecTime() {
        return this.meanExecTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.mean_exec_time</code>.
     */
    public PgStatStatements setMeanExecTime(Double meanExecTime) {
        this.meanExecTime = meanExecTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.stddev_exec_time</code>.
     */
    public Double getStddevExecTime() {
        return this.stddevExecTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.stddev_exec_time</code>.
     */
    public PgStatStatements setStddevExecTime(Double stddevExecTime) {
        this.stddevExecTime = stddevExecTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.rows</code>.
     */
    public Long getRows() {
        return this.rows;
    }

    /**
     * Setter for <code>public.pg_stat_statements.rows</code>.
     */
    public PgStatStatements setRows(Long rows) {
        this.rows = rows;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_hit</code>.
     */
    public Long getSharedBlksHit() {
        return this.sharedBlksHit;
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_hit</code>.
     */
    public PgStatStatements setSharedBlksHit(Long sharedBlksHit) {
        this.sharedBlksHit = sharedBlksHit;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_read</code>.
     */
    public Long getSharedBlksRead() {
        return this.sharedBlksRead;
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_read</code>.
     */
    public PgStatStatements setSharedBlksRead(Long sharedBlksRead) {
        this.sharedBlksRead = sharedBlksRead;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_dirtied</code>.
     */
    public Long getSharedBlksDirtied() {
        return this.sharedBlksDirtied;
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_dirtied</code>.
     */
    public PgStatStatements setSharedBlksDirtied(Long sharedBlksDirtied) {
        this.sharedBlksDirtied = sharedBlksDirtied;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_written</code>.
     */
    public Long getSharedBlksWritten() {
        return this.sharedBlksWritten;
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_written</code>.
     */
    public PgStatStatements setSharedBlksWritten(Long sharedBlksWritten) {
        this.sharedBlksWritten = sharedBlksWritten;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_hit</code>.
     */
    public Long getLocalBlksHit() {
        return this.localBlksHit;
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_hit</code>.
     */
    public PgStatStatements setLocalBlksHit(Long localBlksHit) {
        this.localBlksHit = localBlksHit;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_read</code>.
     */
    public Long getLocalBlksRead() {
        return this.localBlksRead;
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_read</code>.
     */
    public PgStatStatements setLocalBlksRead(Long localBlksRead) {
        this.localBlksRead = localBlksRead;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_dirtied</code>.
     */
    public Long getLocalBlksDirtied() {
        return this.localBlksDirtied;
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_dirtied</code>.
     */
    public PgStatStatements setLocalBlksDirtied(Long localBlksDirtied) {
        this.localBlksDirtied = localBlksDirtied;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_written</code>.
     */
    public Long getLocalBlksWritten() {
        return this.localBlksWritten;
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_written</code>.
     */
    public PgStatStatements setLocalBlksWritten(Long localBlksWritten) {
        this.localBlksWritten = localBlksWritten;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.temp_blks_read</code>.
     */
    public Long getTempBlksRead() {
        return this.tempBlksRead;
    }

    /**
     * Setter for <code>public.pg_stat_statements.temp_blks_read</code>.
     */
    public PgStatStatements setTempBlksRead(Long tempBlksRead) {
        this.tempBlksRead = tempBlksRead;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.temp_blks_written</code>.
     */
    public Long getTempBlksWritten() {
        return this.tempBlksWritten;
    }

    /**
     * Setter for <code>public.pg_stat_statements.temp_blks_written</code>.
     */
    public PgStatStatements setTempBlksWritten(Long tempBlksWritten) {
        this.tempBlksWritten = tempBlksWritten;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.blk_read_time</code>.
     */
    public Double getBlkReadTime() {
        return this.blkReadTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.blk_read_time</code>.
     */
    public PgStatStatements setBlkReadTime(Double blkReadTime) {
        this.blkReadTime = blkReadTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.blk_write_time</code>.
     */
    public Double getBlkWriteTime() {
        return this.blkWriteTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.blk_write_time</code>.
     */
    public PgStatStatements setBlkWriteTime(Double blkWriteTime) {
        this.blkWriteTime = blkWriteTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.temp_blk_read_time</code>.
     */
    public Double getTempBlkReadTime() {
        return this.tempBlkReadTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.temp_blk_read_time</code>.
     */
    public PgStatStatements setTempBlkReadTime(Double tempBlkReadTime) {
        this.tempBlkReadTime = tempBlkReadTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.temp_blk_write_time</code>.
     */
    public Double getTempBlkWriteTime() {
        return this.tempBlkWriteTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.temp_blk_write_time</code>.
     */
    public PgStatStatements setTempBlkWriteTime(Double tempBlkWriteTime) {
        this.tempBlkWriteTime = tempBlkWriteTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.wal_records</code>.
     */
    public Long getWalRecords() {
        return this.walRecords;
    }

    /**
     * Setter for <code>public.pg_stat_statements.wal_records</code>.
     */
    public PgStatStatements setWalRecords(Long walRecords) {
        this.walRecords = walRecords;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.wal_fpi</code>.
     */
    public Long getWalFpi() {
        return this.walFpi;
    }

    /**
     * Setter for <code>public.pg_stat_statements.wal_fpi</code>.
     */
    public PgStatStatements setWalFpi(Long walFpi) {
        this.walFpi = walFpi;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.wal_bytes</code>.
     */
    public BigDecimal getWalBytes() {
        return this.walBytes;
    }

    /**
     * Setter for <code>public.pg_stat_statements.wal_bytes</code>.
     */
    public PgStatStatements setWalBytes(BigDecimal walBytes) {
        this.walBytes = walBytes;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_functions</code>.
     */
    public Long getJitFunctions() {
        return this.jitFunctions;
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_functions</code>.
     */
    public PgStatStatements setJitFunctions(Long jitFunctions) {
        this.jitFunctions = jitFunctions;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_generation_time</code>.
     */
    public Double getJitGenerationTime() {
        return this.jitGenerationTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_generation_time</code>.
     */
    public PgStatStatements setJitGenerationTime(Double jitGenerationTime) {
        this.jitGenerationTime = jitGenerationTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_inlining_count</code>.
     */
    public Long getJitInliningCount() {
        return this.jitInliningCount;
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_inlining_count</code>.
     */
    public PgStatStatements setJitInliningCount(Long jitInliningCount) {
        this.jitInliningCount = jitInliningCount;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_inlining_time</code>.
     */
    public Double getJitInliningTime() {
        return this.jitInliningTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_inlining_time</code>.
     */
    public PgStatStatements setJitInliningTime(Double jitInliningTime) {
        this.jitInliningTime = jitInliningTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_optimization_count</code>.
     */
    public Long getJitOptimizationCount() {
        return this.jitOptimizationCount;
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_optimization_count</code>.
     */
    public PgStatStatements setJitOptimizationCount(Long jitOptimizationCount) {
        this.jitOptimizationCount = jitOptimizationCount;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_optimization_time</code>.
     */
    public Double getJitOptimizationTime() {
        return this.jitOptimizationTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_optimization_time</code>.
     */
    public PgStatStatements setJitOptimizationTime(Double jitOptimizationTime) {
        this.jitOptimizationTime = jitOptimizationTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_emission_count</code>.
     */
    public Long getJitEmissionCount() {
        return this.jitEmissionCount;
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_emission_count</code>.
     */
    public PgStatStatements setJitEmissionCount(Long jitEmissionCount) {
        this.jitEmissionCount = jitEmissionCount;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.jit_emission_time</code>.
     */
    public Double getJitEmissionTime() {
        return this.jitEmissionTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.jit_emission_time</code>.
     */
    public PgStatStatements setJitEmissionTime(Double jitEmissionTime) {
        this.jitEmissionTime = jitEmissionTime;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PgStatStatements other = (PgStatStatements) obj;
        if (this.userid == null) {
            if (other.userid != null)
                return false;
        }
        else if (!this.userid.equals(other.userid))
            return false;
        if (this.dbid == null) {
            if (other.dbid != null)
                return false;
        }
        else if (!this.dbid.equals(other.dbid))
            return false;
        if (this.toplevel == null) {
            if (other.toplevel != null)
                return false;
        }
        else if (!this.toplevel.equals(other.toplevel))
            return false;
        if (this.queryid == null) {
            if (other.queryid != null)
                return false;
        }
        else if (!this.queryid.equals(other.queryid))
            return false;
        if (this.query == null) {
            if (other.query != null)
                return false;
        }
        else if (!this.query.equals(other.query))
            return false;
        if (this.plans == null) {
            if (other.plans != null)
                return false;
        }
        else if (!this.plans.equals(other.plans))
            return false;
        if (this.totalPlanTime == null) {
            if (other.totalPlanTime != null)
                return false;
        }
        else if (!this.totalPlanTime.equals(other.totalPlanTime))
            return false;
        if (this.minPlanTime == null) {
            if (other.minPlanTime != null)
                return false;
        }
        else if (!this.minPlanTime.equals(other.minPlanTime))
            return false;
        if (this.maxPlanTime == null) {
            if (other.maxPlanTime != null)
                return false;
        }
        else if (!this.maxPlanTime.equals(other.maxPlanTime))
            return false;
        if (this.meanPlanTime == null) {
            if (other.meanPlanTime != null)
                return false;
        }
        else if (!this.meanPlanTime.equals(other.meanPlanTime))
            return false;
        if (this.stddevPlanTime == null) {
            if (other.stddevPlanTime != null)
                return false;
        }
        else if (!this.stddevPlanTime.equals(other.stddevPlanTime))
            return false;
        if (this.calls == null) {
            if (other.calls != null)
                return false;
        }
        else if (!this.calls.equals(other.calls))
            return false;
        if (this.totalExecTime == null) {
            if (other.totalExecTime != null)
                return false;
        }
        else if (!this.totalExecTime.equals(other.totalExecTime))
            return false;
        if (this.minExecTime == null) {
            if (other.minExecTime != null)
                return false;
        }
        else if (!this.minExecTime.equals(other.minExecTime))
            return false;
        if (this.maxExecTime == null) {
            if (other.maxExecTime != null)
                return false;
        }
        else if (!this.maxExecTime.equals(other.maxExecTime))
            return false;
        if (this.meanExecTime == null) {
            if (other.meanExecTime != null)
                return false;
        }
        else if (!this.meanExecTime.equals(other.meanExecTime))
            return false;
        if (this.stddevExecTime == null) {
            if (other.stddevExecTime != null)
                return false;
        }
        else if (!this.stddevExecTime.equals(other.stddevExecTime))
            return false;
        if (this.rows == null) {
            if (other.rows != null)
                return false;
        }
        else if (!this.rows.equals(other.rows))
            return false;
        if (this.sharedBlksHit == null) {
            if (other.sharedBlksHit != null)
                return false;
        }
        else if (!this.sharedBlksHit.equals(other.sharedBlksHit))
            return false;
        if (this.sharedBlksRead == null) {
            if (other.sharedBlksRead != null)
                return false;
        }
        else if (!this.sharedBlksRead.equals(other.sharedBlksRead))
            return false;
        if (this.sharedBlksDirtied == null) {
            if (other.sharedBlksDirtied != null)
                return false;
        }
        else if (!this.sharedBlksDirtied.equals(other.sharedBlksDirtied))
            return false;
        if (this.sharedBlksWritten == null) {
            if (other.sharedBlksWritten != null)
                return false;
        }
        else if (!this.sharedBlksWritten.equals(other.sharedBlksWritten))
            return false;
        if (this.localBlksHit == null) {
            if (other.localBlksHit != null)
                return false;
        }
        else if (!this.localBlksHit.equals(other.localBlksHit))
            return false;
        if (this.localBlksRead == null) {
            if (other.localBlksRead != null)
                return false;
        }
        else if (!this.localBlksRead.equals(other.localBlksRead))
            return false;
        if (this.localBlksDirtied == null) {
            if (other.localBlksDirtied != null)
                return false;
        }
        else if (!this.localBlksDirtied.equals(other.localBlksDirtied))
            return false;
        if (this.localBlksWritten == null) {
            if (other.localBlksWritten != null)
                return false;
        }
        else if (!this.localBlksWritten.equals(other.localBlksWritten))
            return false;
        if (this.tempBlksRead == null) {
            if (other.tempBlksRead != null)
                return false;
        }
        else if (!this.tempBlksRead.equals(other.tempBlksRead))
            return false;
        if (this.tempBlksWritten == null) {
            if (other.tempBlksWritten != null)
                return false;
        }
        else if (!this.tempBlksWritten.equals(other.tempBlksWritten))
            return false;
        if (this.blkReadTime == null) {
            if (other.blkReadTime != null)
                return false;
        }
        else if (!this.blkReadTime.equals(other.blkReadTime))
            return false;
        if (this.blkWriteTime == null) {
            if (other.blkWriteTime != null)
                return false;
        }
        else if (!this.blkWriteTime.equals(other.blkWriteTime))
            return false;
        if (this.tempBlkReadTime == null) {
            if (other.tempBlkReadTime != null)
                return false;
        }
        else if (!this.tempBlkReadTime.equals(other.tempBlkReadTime))
            return false;
        if (this.tempBlkWriteTime == null) {
            if (other.tempBlkWriteTime != null)
                return false;
        }
        else if (!this.tempBlkWriteTime.equals(other.tempBlkWriteTime))
            return false;
        if (this.walRecords == null) {
            if (other.walRecords != null)
                return false;
        }
        else if (!this.walRecords.equals(other.walRecords))
            return false;
        if (this.walFpi == null) {
            if (other.walFpi != null)
                return false;
        }
        else if (!this.walFpi.equals(other.walFpi))
            return false;
        if (this.walBytes == null) {
            if (other.walBytes != null)
                return false;
        }
        else if (!this.walBytes.equals(other.walBytes))
            return false;
        if (this.jitFunctions == null) {
            if (other.jitFunctions != null)
                return false;
        }
        else if (!this.jitFunctions.equals(other.jitFunctions))
            return false;
        if (this.jitGenerationTime == null) {
            if (other.jitGenerationTime != null)
                return false;
        }
        else if (!this.jitGenerationTime.equals(other.jitGenerationTime))
            return false;
        if (this.jitInliningCount == null) {
            if (other.jitInliningCount != null)
                return false;
        }
        else if (!this.jitInliningCount.equals(other.jitInliningCount))
            return false;
        if (this.jitInliningTime == null) {
            if (other.jitInliningTime != null)
                return false;
        }
        else if (!this.jitInliningTime.equals(other.jitInliningTime))
            return false;
        if (this.jitOptimizationCount == null) {
            if (other.jitOptimizationCount != null)
                return false;
        }
        else if (!this.jitOptimizationCount.equals(other.jitOptimizationCount))
            return false;
        if (this.jitOptimizationTime == null) {
            if (other.jitOptimizationTime != null)
                return false;
        }
        else if (!this.jitOptimizationTime.equals(other.jitOptimizationTime))
            return false;
        if (this.jitEmissionCount == null) {
            if (other.jitEmissionCount != null)
                return false;
        }
        else if (!this.jitEmissionCount.equals(other.jitEmissionCount))
            return false;
        if (this.jitEmissionTime == null) {
            if (other.jitEmissionTime != null)
                return false;
        }
        else if (!this.jitEmissionTime.equals(other.jitEmissionTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userid == null) ? 0 : this.userid.hashCode());
        result = prime * result + ((this.dbid == null) ? 0 : this.dbid.hashCode());
        result = prime * result + ((this.toplevel == null) ? 0 : this.toplevel.hashCode());
        result = prime * result + ((this.queryid == null) ? 0 : this.queryid.hashCode());
        result = prime * result + ((this.query == null) ? 0 : this.query.hashCode());
        result = prime * result + ((this.plans == null) ? 0 : this.plans.hashCode());
        result = prime * result + ((this.totalPlanTime == null) ? 0 : this.totalPlanTime.hashCode());
        result = prime * result + ((this.minPlanTime == null) ? 0 : this.minPlanTime.hashCode());
        result = prime * result + ((this.maxPlanTime == null) ? 0 : this.maxPlanTime.hashCode());
        result = prime * result + ((this.meanPlanTime == null) ? 0 : this.meanPlanTime.hashCode());
        result = prime * result + ((this.stddevPlanTime == null) ? 0 : this.stddevPlanTime.hashCode());
        result = prime * result + ((this.calls == null) ? 0 : this.calls.hashCode());
        result = prime * result + ((this.totalExecTime == null) ? 0 : this.totalExecTime.hashCode());
        result = prime * result + ((this.minExecTime == null) ? 0 : this.minExecTime.hashCode());
        result = prime * result + ((this.maxExecTime == null) ? 0 : this.maxExecTime.hashCode());
        result = prime * result + ((this.meanExecTime == null) ? 0 : this.meanExecTime.hashCode());
        result = prime * result + ((this.stddevExecTime == null) ? 0 : this.stddevExecTime.hashCode());
        result = prime * result + ((this.rows == null) ? 0 : this.rows.hashCode());
        result = prime * result + ((this.sharedBlksHit == null) ? 0 : this.sharedBlksHit.hashCode());
        result = prime * result + ((this.sharedBlksRead == null) ? 0 : this.sharedBlksRead.hashCode());
        result = prime * result + ((this.sharedBlksDirtied == null) ? 0 : this.sharedBlksDirtied.hashCode());
        result = prime * result + ((this.sharedBlksWritten == null) ? 0 : this.sharedBlksWritten.hashCode());
        result = prime * result + ((this.localBlksHit == null) ? 0 : this.localBlksHit.hashCode());
        result = prime * result + ((this.localBlksRead == null) ? 0 : this.localBlksRead.hashCode());
        result = prime * result + ((this.localBlksDirtied == null) ? 0 : this.localBlksDirtied.hashCode());
        result = prime * result + ((this.localBlksWritten == null) ? 0 : this.localBlksWritten.hashCode());
        result = prime * result + ((this.tempBlksRead == null) ? 0 : this.tempBlksRead.hashCode());
        result = prime * result + ((this.tempBlksWritten == null) ? 0 : this.tempBlksWritten.hashCode());
        result = prime * result + ((this.blkReadTime == null) ? 0 : this.blkReadTime.hashCode());
        result = prime * result + ((this.blkWriteTime == null) ? 0 : this.blkWriteTime.hashCode());
        result = prime * result + ((this.tempBlkReadTime == null) ? 0 : this.tempBlkReadTime.hashCode());
        result = prime * result + ((this.tempBlkWriteTime == null) ? 0 : this.tempBlkWriteTime.hashCode());
        result = prime * result + ((this.walRecords == null) ? 0 : this.walRecords.hashCode());
        result = prime * result + ((this.walFpi == null) ? 0 : this.walFpi.hashCode());
        result = prime * result + ((this.walBytes == null) ? 0 : this.walBytes.hashCode());
        result = prime * result + ((this.jitFunctions == null) ? 0 : this.jitFunctions.hashCode());
        result = prime * result + ((this.jitGenerationTime == null) ? 0 : this.jitGenerationTime.hashCode());
        result = prime * result + ((this.jitInliningCount == null) ? 0 : this.jitInliningCount.hashCode());
        result = prime * result + ((this.jitInliningTime == null) ? 0 : this.jitInliningTime.hashCode());
        result = prime * result + ((this.jitOptimizationCount == null) ? 0 : this.jitOptimizationCount.hashCode());
        result = prime * result + ((this.jitOptimizationTime == null) ? 0 : this.jitOptimizationTime.hashCode());
        result = prime * result + ((this.jitEmissionCount == null) ? 0 : this.jitEmissionCount.hashCode());
        result = prime * result + ((this.jitEmissionTime == null) ? 0 : this.jitEmissionTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgStatStatements (");

        sb.append(userid);
        sb.append(", ").append(dbid);
        sb.append(", ").append(toplevel);
        sb.append(", ").append(queryid);
        sb.append(", ").append(query);
        sb.append(", ").append(plans);
        sb.append(", ").append(totalPlanTime);
        sb.append(", ").append(minPlanTime);
        sb.append(", ").append(maxPlanTime);
        sb.append(", ").append(meanPlanTime);
        sb.append(", ").append(stddevPlanTime);
        sb.append(", ").append(calls);
        sb.append(", ").append(totalExecTime);
        sb.append(", ").append(minExecTime);
        sb.append(", ").append(maxExecTime);
        sb.append(", ").append(meanExecTime);
        sb.append(", ").append(stddevExecTime);
        sb.append(", ").append(rows);
        sb.append(", ").append(sharedBlksHit);
        sb.append(", ").append(sharedBlksRead);
        sb.append(", ").append(sharedBlksDirtied);
        sb.append(", ").append(sharedBlksWritten);
        sb.append(", ").append(localBlksHit);
        sb.append(", ").append(localBlksRead);
        sb.append(", ").append(localBlksDirtied);
        sb.append(", ").append(localBlksWritten);
        sb.append(", ").append(tempBlksRead);
        sb.append(", ").append(tempBlksWritten);
        sb.append(", ").append(blkReadTime);
        sb.append(", ").append(blkWriteTime);
        sb.append(", ").append(tempBlkReadTime);
        sb.append(", ").append(tempBlkWriteTime);
        sb.append(", ").append(walRecords);
        sb.append(", ").append(walFpi);
        sb.append(", ").append(walBytes);
        sb.append(", ").append(jitFunctions);
        sb.append(", ").append(jitGenerationTime);
        sb.append(", ").append(jitInliningCount);
        sb.append(", ").append(jitInliningTime);
        sb.append(", ").append(jitOptimizationCount);
        sb.append(", ").append(jitOptimizationTime);
        sb.append(", ").append(jitEmissionCount);
        sb.append(", ").append(jitEmissionTime);

        sb.append(")");
        return sb.toString();
    }
}
