/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgStatStatementsInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long dealloc;
    private OffsetDateTime statsReset;

    public PgStatStatementsInfo() {}

    public PgStatStatementsInfo(PgStatStatementsInfo value) {
        this.dealloc = value.dealloc;
        this.statsReset = value.statsReset;
    }

    public PgStatStatementsInfo(
        Long dealloc,
        OffsetDateTime statsReset
    ) {
        this.dealloc = dealloc;
        this.statsReset = statsReset;
    }

    /**
     * Getter for <code>public.pg_stat_statements_info.dealloc</code>.
     */
    public Long getDealloc() {
        return this.dealloc;
    }

    /**
     * Setter for <code>public.pg_stat_statements_info.dealloc</code>.
     */
    public PgStatStatementsInfo setDealloc(Long dealloc) {
        this.dealloc = dealloc;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements_info.stats_reset</code>.
     */
    public OffsetDateTime getStatsReset() {
        return this.statsReset;
    }

    /**
     * Setter for <code>public.pg_stat_statements_info.stats_reset</code>.
     */
    public PgStatStatementsInfo setStatsReset(OffsetDateTime statsReset) {
        this.statsReset = statsReset;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PgStatStatementsInfo other = (PgStatStatementsInfo) obj;
        if (this.dealloc == null) {
            if (other.dealloc != null)
                return false;
        }
        else if (!this.dealloc.equals(other.dealloc))
            return false;
        if (this.statsReset == null) {
            if (other.statsReset != null)
                return false;
        }
        else if (!this.statsReset.equals(other.statsReset))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.dealloc == null) ? 0 : this.dealloc.hashCode());
        result = prime * result + ((this.statsReset == null) ? 0 : this.statsReset.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgStatStatementsInfo (");

        sb.append(dealloc);
        sb.append(", ").append(statsReset);

        sb.append(")");
        return sb.toString();
    }
}
