/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.xpendence.jooqexample.domain.Keys;
import ru.xpendence.jooqexample.domain.Public;
import ru.xpendence.jooqexample.domain.tables.records.CitiesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Cities extends TableImpl<CitiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.cities</code>
     */
    public static final Cities CITIES = new Cities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CitiesRecord> getRecordType() {
        return CitiesRecord.class;
    }

    /**
     * The column <code>public.cities.id</code>.
     */
    public final TableField<CitiesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.cities.country_id</code>.
     */
    public final TableField<CitiesRecord, Long> COUNTRY_ID = createField(DSL.name("country_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.cities.name</code>.
     */
    public final TableField<CitiesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    private Cities(Name alias, Table<CitiesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Cities(Name alias, Table<CitiesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.cities</code> table reference
     */
    public Cities(String alias) {
        this(DSL.name(alias), CITIES);
    }

    /**
     * Create an aliased <code>public.cities</code> table reference
     */
    public Cities(Name alias) {
        this(alias, CITIES);
    }

    /**
     * Create a <code>public.cities</code> table reference
     */
    public Cities() {
        this(DSL.name("cities"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CitiesRecord, Long> getIdentity() {
        return (Identity<CitiesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CitiesRecord> getPrimaryKey() {
        return Keys.CITIES_PKEY;
    }

    @Override
    public Cities as(String alias) {
        return new Cities(DSL.name(alias), this);
    }

    @Override
    public Cities as(Name alias) {
        return new Cities(alias, this);
    }

    @Override
    public Cities as(Table<?> alias) {
        return new Cities(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cities rename(String name) {
        return new Cities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cities rename(Name name) {
        return new Cities(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cities rename(Table<?> name) {
        return new Cities(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cities where(Condition condition) {
        return new Cities(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cities where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cities where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cities where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cities where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cities where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cities where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cities where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cities whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cities whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
